# -*- coding: utf-8 -*-
"""Compro Pertemuan 4, String Part 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B3deS_VJDuzvMHKuiDa_1WcFYIoRElQU

**Format Specifiers**
"""

template = 'Halo, saya %s dari %s'
print(template % ('Lendis Fabri', 'Indonesia'))

"""**Fungsi String Format**"""

template = 'Halo, saya {nama} dari {asal}'
template_2 = 'Saya suka makan {} dan minum {}'

print(template.format(nama='Lendis Fabri', asal='Indonesia'))
print(template_2.format('Nasi Goreng', 'air mineral'))

"""**String Interpolation / F-**"""

nama = 'Lendis Fabri'
asal = 'indonesia'

print(f'Perkenalkan saya {nama} dari {asal}')

"""**Memecah String Menjadi List dan sebaliknya**"""

alamat = 'Surabaya, Jawa Timur, Indonesia'

print(alamat.split())

print(alamat.split(','))

print(alamat.split(', '))

"""**Memecah String Menjadi List dan sebaliknya**"""

print('<3'.join(['aku', 'suka', 'python']))

print('rawr'.join(alamat.split(', ')))

"""**Mengubah String Menjadi Upper dan Lower Case**


"""

print('halo selamat pagi!'.upper())
print('Halo Selamat Siang!'.upper())


print('APA KABAR?'.lower())
print('Lagi Dimana?'.lower())

"""**Mengubah String Menjadi Title Case**"""

print('daun tidak pernah membenci angin'.title())
print('LASKAR PELANGI'.title())

"""**Mengubah String menjadi REVERSE case**"""

print('Indonesia Adalah Negara Kepulauan'.swapcase())
print('aKU cInTa NEgErIkU'.swapcase())

"""**Mencari Kata Pada String**"""

angka = '12345'

print('Index angka 3:', angka.find('3'))
print('Index angka 45:', angka.find('45'))
print('Index angka 35:', angka.find('35'))

asal = 'Lampungu'
print(asal.find('a'))
print(asal.find('u'))
print(asal.find('pung'))
print(asal.find('langu'))

"""**Mereplace Kata Pada String**"""

ibu_kota = 'Jakarta'

print(ibu_kota.replace('a', 'i'))
print(ibu_kota.replace('kar', 'emuach'))

"""**Menghapus kara tertentu pada string**"""

ibu_kota = 'Jakarta'

print(ibu_kota.replace('a', ''))

"""**Menghitung Jumlah Karakter Yang Muncul**"""

paragraf = 'Baru-baru ini telah ditemukan sebuah meteor di suatu sungai'
x = paragraf.count('di')

print(f'Kata "di" muncul sebanyak {x} kali')