# -*- coding: utf-8 -*-
"""Manipulasi String.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lZqTGuR7tO3oHi-v0wA9U-aGFamc1EK_

String
"""

nama = 'Anggita Prasastya W'
asal = "Indonesia"

print(nama)

print(asal)

"""**Manipulasi String**"""

print(nama, asal)

print(nama + asal)

print("Halo, nama saya",nama)

print("Halo, nama saya",nama, "asal saya dari", asal)

data_lengkap = nama + asal

print(data_lengkap)

data_lengkap_banget_fix_final = nama + asal
dataLengkapBanget
DataLengkap

"""**String + Non String**"""

asal_kota = "Bandar Lampung"
kode_pos = 35144


asal_kota_kode_pos = asal_kota + str(kode_pos)
print(asal_kota_kode_pos)

asal_kota_x3 = asal_kota * 3
print(asal_kota_x3)